### ISSUE TITLE
String '8/13/2024' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by danielavdalian** [Poushec/Poushec.UpdateCatalogParser#7]
![image](https://github.com/user-attachments/assets/bb74a86d-4685-417a-9877-2b236b22c1d5)

**Comment by Poushec** [comment]
Hi! Does it work with this query? It should return the only update with 9/10/2024 date 

`388635e1-8b00-4bfd-8839-ebd7443ad16e`

**Comment by Poushec** [comment]
Hey @danielavdalian 

I've added optional CultureInfo parameter to the CatalogClient that defaults to `en-US`. This should resolve the issue you're having
