### ISSUE TITLE
Download Link Regex Missing Certain Updates

### ISSUE THREAD

**Issue by sapientem** [Poushec/Poushec.UpdateCatalogParser#9]
Newer (I think?) updates from the catalog use a different subdomain structure:

https://catalog.sf.dl.delivery.mp.microsoft.com

One update that uses this is KB5039212. Fixed regex for _downloadLinkRegex in CatalogParser:

`private readonly Regex _downloadLinkRegex = new Regex(@"(http[s]?\://dl\.delivery\.mp\.microsoft\.com\/[^\'\""]*)|(http[s]?\://download\.windowsupdate\.com\/[^\'\""]*)|(http[s]?\://catalog\.s\.download\.windowsupdate\.com.*?(?=\'))|(http[s]?\://catalog\.sf\.dl\.delivery\.mp\.microsoft\.com\/[^\'\""]*)");`

Thank you.

**Comment by Poushec** [comment]
Hey @sapientem, thanks for your suggestion! 

I'm wondering, do we actually need to have such a strict pattern? What stopping us from using something like this `https?:\/\/.*?(?=')` that would simply match any link starting with http/https? 

I don't think there's any other links within these download pages.

**Comment by Poushec** [comment]
Updated the pattern in v4.0.3 - will see if we hit any edge cases with this pattern. 

Thanks again @sapientem for letting me know!

**Comment by Poushec** [comment]
Glad it helped you. :)
